export const Language = {
  ASAMI: "Asami",
  BENGALI: "Bengali",
  GUJARATI: "Gujarati",
  HINDI: "Hindi",
  KANNADA: "Kannada",
  MALAYALAM: "Malayalam",
  MARATHI: "Marathi",
  ODIA: "Odia",
  PUNJABI: "Punjabi",
  TAMIL: "Tamil",
  TELUGU: "Telugu",
  URDU: "Urdu",
  SANSKRIT: "Sanskrit",
  ENGLISH: "English",
  KONKANI: "Konkani",
  NEPALI: "Nepali",
  BODO: "Bodo",
  KASHMIRI: "Kashmiri",
  MAITHILI: "Maithili",
  SANTALI: "Santali",
  SINDHI: "Sindhi",
};
